version: '3'
services:

# ................ nginx ..................

  nginx:
    build: requirements/nginx/
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html/wordpress
    depends_on:
      - wordpress
    networks:
      - inception
    restart: always

# ................ wordpress ..................

  wordpress:
    build: requirements/wordpress/
    container_name: wordpress
    ports:
      - "9000:9000"
    volumes:
      - wordpress:/var/www/html/wordpress
    depends_on:
      - mariadb
    networks:
      - inception
    restart: always
    environment:
      MYSQL_HOST:       ${MYSQL_HOST}
      WP_DATABASE_NAME: ${WP_DATABASE_NAME}
      WP_DATABASE_USR:  ${WP_DATABASE_USR}
      WP_DATABASE_PWD:  ${WP_DATABASE_PWD}
      DOMAIN_NAME:      ${DOMAIN_NAME}
      WP_TITLE:         ${WP_TITLE}
      WP_ADMIN_USR:     ${WP_ADMIN_USR}
      WP_ADMIN_PWD:     ${WP_ADMIN_PWD}
      WP_ADMIN_EMAIL:   ${WP_ADMIN_EMAIL}
      WP_USR:           ${WP_USR}
      WP_PWD:           ${WP_PWD}
      WP_EMAIL:         ${WP_EMAIL}

# ................ mariaDB ..................

  mariadb:
    build: requirements/mariadb/
    container_name: mariadb
    ports:
      - "3306:3306"
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    restart: always
    environment:
      MYSQL_ROOT_PWD:   ${MYSQL_ROOT_PWD}
      WP_DATABASE_NAME: ${WP_DATABASE_NAME}
      WP_DATABASE_USR:  ${WP_DATABASE_USR}
      WP_DATABASE_PWD:  ${WP_DATABASE_PWD}
    
  
# _______________ NETWORKS____________________

networks:

  inception:
    driver: bridge
    name: inception

# _________________ VOLUMES __________________

volumes:

  wordpress:
    driver: local
    name: wordpress
    driver_opts:
      type: none
      o: bind
      device: /home/mpagani/data/wordpress
  
  mariadb:
    driver: local
    name: mariadb
    driver_opts:
      type: none
      o: bind
      device: /home/mpagani/data/mariadb

